version: '3'
services:
  alex-api:
    build:
      context: ./alex-api
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"

  alex-manager:
    build:
      context: ./alex-manager
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"