# Generated by Django 5.0.4 on 2024-04-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_book_availability_book_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(),
        ),
    ]
