# Generated by Django 5.0.4 on 2024-05-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifetime', models.IntegerField(default=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.user')),
            ],
            options={
                'db_table': 'alex_demo_loan_token',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.book')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.loantoken')),
            ],
            options={
                'db_table': 'alex_demo_loan',
            },
        ),
    ]
