# Generated by Django 5.0.4 on 2024-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_loantoken_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('AVA', 'Available'), ('LOA', 'Loaned'), ('RES', 'Reserved'), ('LOS', 'Lost'), ('STO', 'In Storage')], default='Available', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='BookAvailability',
        ),
    ]
