# Generated by Django 5.0.4 on 2024-05-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_book_availability_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the author is currently active in the system.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the author record was created.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='First name of the author.', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the author.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='Last name of the author.', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the author record was last updated.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the book is currently active.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='Authors associated with the book.', related_name='books', to='server.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('AVA', 'Available'), ('LOA', 'Loaned'), ('RES', 'Reserved'), ('LOS', 'Lost'), ('STO', 'In Storage')], default='Available', help_text='Availability status of the book.', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, help_text="URL of the book's cover image.", null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the book record was created.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='editions',
            field=models.IntegerField(default=1, help_text='Number of editions of the book.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the book.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='International Standard Book Number (ISBN) of the book.', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, help_text='Date when the book was published.', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Publisher of the book.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='server.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(help_text='Shelf where the book is located.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='server.shelf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.ForeignKey(help_text='State of the book.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='server.bookstate'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Title of the book.', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the book record was last updated.'),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the book state is currently active in the system.'),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the book state record was created.'),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the book state.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='name',
            field=models.CharField(help_text='Name of the book state.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the book state record was last updated.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the loan is currently active.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(help_text='Book associated with the loan.', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the loan was created.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the loan.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='token',
            field=models.ForeignKey(help_text='Loan token associated with the loan.', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.loantoken'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the loan was last updated.'),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the loan token was created.'),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the loan token.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='lifetime',
            field=models.IntegerField(default=7, help_text='Duration in days for which the token is valid.'),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='token',
            field=models.CharField(help_text='Unique token generated for the loan.', max_length=255),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the loan token was last updated.'),
        ),
        migrations.AlterField(
            model_name='loantoken',
            name='user',
            field=models.ForeignKey(help_text='User associated with the loan token.', on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='server.user'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the publisher is currently active in the system.'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the publisher record was created.'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the publisher.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='Name of the publishing house.', max_length=255),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the publisher record was last updated.'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='active',
            field=models.BooleanField(default=True, help_text='Indicates whether the shelf is currently active in the system.'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the shelf record was created.'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the shelf.', null=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the shelf.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='name',
            field=models.CharField(help_text='Name of the shelf.', max_length=255),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the shelf record was last updated.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the user account was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text="User's email address.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="User's first name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the user.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the user account is active.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indicates whether the user is a staff member.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indicates whether the user has superuser privileges.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, help_text="Timestamp of the user's last login."),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="User's last name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text="User's password.", max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username.', max_length=255),
        ),
    ]
