# Generated by Django 5.0.4 on 2024-05-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_author_active_alter_author_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
    ]
