# Generated by Django 5.0.6 on 2024-05-09 13:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_loantoken_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='render_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 8, 13, 32, 3, 148556, tzinfo=datetime.timezone.utc), help_text='Date when the book must be returned.'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the reservation.', primary_key=True, serialize=False)),
                ('availability_date', models.DateField(blank=True, help_text='Date when the book will be available.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when the reservation was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp indicating when the reservation was last updated.')),
                ('book', models.ForeignKey(help_text='Book associated with the reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='server.book')),
                ('token', models.ForeignKey(help_text='Loan token associated with the reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='server.loantoken')),
            ],
            options={
                'db_table': 'alex_demo_reservation',
            },
        ),
    ]
