# Generated by Django 5.0.6 on 2024-05-09 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_loan_render_date_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='render_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 8, 13, 34, 49, 722789, tzinfo=datetime.timezone.utc), help_text='Date when the book must be returned.'),
        ),
    ]
