name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alex-api/requirements.txt
    - name: Create env file
      run: |
        cd alex-api/api
        touch .env
        echo ALEX_HOST = 127.0.0.1 >> .env
        echo ALEX_PORT = 8000 >> .env
        cat .env
    - name: Run Tests
      run: |
        cd alex-api/api
        python manage.py migrate
        python manage.py test server/test
